package com.voteU.election.java.entities.electiondata;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
@Table(name = "candidates")
public class Candidates {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // autogenerated primary key

    @Column(name = "candidate_id")
    private int candidateId;

    @Column(name = "party_id", nullable = false)
    private Integer partyId;

    @Column(name = "election_id", length = 255, nullable = false)
    private String electionId;

    @Column(name = "first_name", nullable = false)
    private String firstName;

    @Column(name = "last_name", nullable = false)
    private String lastName;

    @Column(name = "gender")
    private String gender;

    @Column(name = "locality_name")
    private String localityName;

    public Candidates() {}
}
