package com.voteU.election.java.entities.electiondata;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
@Table(name = "national_candidate_votes")
public class NationalCandidateVotes {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // autogenerated ID


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
            @JoinColumn(name = "candidate_id", referencedColumnName = "candidate_id", insertable = false, updatable = false),
            @JoinColumn(name = "election_id", referencedColumnName = "election_id", insertable = false, updatable = false)
    })
    private Candidates candidate;

    @Column(name = "candidate_id")
    private Integer candidateId;

    @Column(name = "party_id", nullable = false)
    private Integer partyId;

    @Column(name = "election_id", length = 255, nullable = false)
    private String electionId;

    @Column(name = "votes")
    private Integer votes;

    public NationalCandidateVotes() {}
}
