package com.voteU.election.java.entities.electiondata;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
@Table(name = "national_party_votes")
public class NationalPartyVotes {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // autogenerated ID

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "party_id", referencedColumnName = "party_id", nullable = false, insertable = false, updatable = false)
    private Parties party;

    @Column(name = "party_id", nullable = false)
    private Integer partyId;

    @Column(name = "election_id", length = 255, nullable = false)
    private String electionId;

    @Column(name = "votes")
    private int votes;

    public NationalPartyVotes() {}
}
