export * from './Affiliation.ts'
export * from './Candidate.ts'
export * from './Constituency.ts'
export * from './Election.ts'
export * from './Municipality.ts'
export * from './PollingStation.ts'
export * from './Province.ts'
