package com.voteU.election.java.database.DBTables;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
@Table(name = "parties",
        uniqueConstraints = @UniqueConstraint(columnNames = {"party_id", "election_id"}))
public class Parties {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // autogenerated unique ID

    @Column(name = "party_id", nullable = false)
    private Integer partyId; // your original party_id, not PK here

    @Column(name = "election_id", length = 255, nullable = false)
    private String electionId;

    @Column(name = "name", nullable = false)
    private String name;

    public Parties() {}
}
