export { default as AboutView } from './AboutView.vue'
export { default as ComparisonView } from './ComparisonView.vue'
export { default as FilterView } from './FilterView.vue'
export { default as ForumView } from './ForumView.vue'
export { default as HomeView } from './HomeView.vue'
export { default as HowView } from './HowView.vue'
export { default as LoginView } from './LoginView.vue'
export { default as RegistrationView } from './RegistrationView.vue'
